trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSource: "spec"
      versionSpec: "20.x"
      checkLatest: true
    displayName: "Install Node.js"
  - script: |
      npm install
    displayName: "instalar dependencias"
  - script: |
      npm run basic-lint
    displayName: "lint"
  - script: |
      npm run test
    displayName: "test"
  - script: |
      npm run format
    displayName: "format"
  - script: |
      npm run review
    displayName: "review"
